"use client";
import { useMemo, useState } from "react";
import { Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { StudentWorkspaceHeader } from "@/components/student/student-workspace-header";
type CatalogCourse = { id: string; title: string; description: string; teacher: string; subject: string; subjectCode: string };
export function CourseCatalog({ courses }: { courses: CatalogCourse[] }) {
  const [query, setQuery] = useState(""); const [subject, setSubject] = useState("All subjects");
  const subjects = useMemo(() => ["All subjects", ...Array.from(new Set(courses.map((course) => course.subject))).sort()], [courses]);
  const visibleCourses = useMemo(() => { const normalized = query.trim().toLowerCase(); return courses.filter((course) => (subject === "All subjects" || course.subject === subject) && (!normalized || [course.title, course.description, course.teacher, course.subject].some((value) => value.toLowerCase().includes(normalized)))); }, [courses, query, subject]);
  return <div className="flex flex-col gap-6"><StudentWorkspaceHeader eyebrow="Learning programs" title="Course catalog" description="Explore the published courses available to your class and find the subject that supports your next goal." metrics={[{ label: "Courses available", value: courses.length, detail: "Published for your class", tone: "primary" }, { label: "Subjects", value: subjects.length - 1, detail: "Areas you can explore", tone: "success" }, { label: "Showing", value: visibleCourses.length, detail: query || subject !== "All subjects" ? "Matching your filters" : "All available courses", tone: "info" }]} /><div className="surface-subtle flex flex-col gap-3 rounded-2xl border border-border/70 p-4 sm:flex-row sm:items-center"><div className="relative max-w-md flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} className="pl-9" placeholder="Search courses, subjects, or teachers..." /></div><select value={subject} onChange={(event) => setSubject(event.target.value)} className="h-10 rounded-xl border border-input bg-card px-3 text-sm outline-none focus:ring-4 focus:ring-ring/15">{subjects.map((item) => <option key={item}>{item}</option>)}</select></div>{visibleCourses.length === 0 ? <Card><CardContent className="py-10 text-center text-sm text-muted-foreground">No published courses match your search.</CardContent></Card> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{visibleCourses.map((course) => <Card key={course.id} className="transition-transform hover:-translate-y-0.5"><CardHeader className="gap-2"><Badge variant="default">{course.subjectCode || course.subject}</Badge><CardTitle>{course.title}</CardTitle></CardHeader><CardContent className="flex flex-1 flex-col gap-3"><p className="line-clamp-3 text-sm text-muted-foreground">{course.description || "Course details will be shared by your teacher."}</p><p className="mt-auto text-xs font-medium text-muted-foreground">Teacher: {course.teacher}</p></CardContent></Card>)}</div>}</div>;
}
