import { notFound } from "next/navigation";
import { getInvoiceById } from "@/lib/data/subscription.data";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { InvoiceActions } from "./invoice-actions";

export default async function InvoiceDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const invoice = await getInvoiceById(id); if (!invoice) notFound();
  const institute = invoice.instituteId as unknown as { name?: string; code?: string } | null; const plan = invoice.planId as unknown as { name?: string } | null; const displayStatus = invoice.status === "pending" && invoice.dueAt < new Date() ? "overdue" : invoice.status;
  return <div className="mx-auto flex w-full max-w-2xl flex-col gap-6"><Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle>{invoice.invoiceNumber}</CardTitle><Badge variant={displayStatus === "paid" ? "success" : displayStatus === "overdue" ? "destructive" : "secondary"} className="capitalize">{displayStatus}</Badge></CardHeader><CardContent><dl className="grid grid-cols-[auto_1fr] gap-x-5 gap-y-2 text-sm"><dt className="text-muted-foreground">Institute</dt><dd>{institute?.name ?? "Unknown"} {institute?.code ? `(${institute.code})` : ""}</dd><dt className="text-muted-foreground">Plan</dt><dd>{invoice.planNameSnapshot || plan?.name}</dd><dt className="text-muted-foreground">Amount</dt><dd>{invoice.currency} {invoice.amount.toFixed(2)}</dd><dt className="text-muted-foreground">Period</dt><dd>{new Date(invoice.periodStart).toLocaleDateString()} – {new Date(invoice.periodEnd).toLocaleDateString()}</dd><dt className="text-muted-foreground">Issued</dt><dd>{new Date(invoice.issuedAt).toLocaleDateString()}</dd><dt className="text-muted-foreground">Due</dt><dd>{new Date(invoice.dueAt).toLocaleDateString()}</dd>{invoice.paidAt ? <><dt className="text-muted-foreground">Paid</dt><dd>{new Date(invoice.paidAt).toLocaleDateString()} via {invoice.paymentMethod?.replace("-", " ")}</dd></> : null}{invoice.receiptNumber ? <><dt className="text-muted-foreground">Receipt</dt><dd>{invoice.receiptNumber}</dd></> : null}{invoice.discountAmount ? <><dt className="text-muted-foreground">Discount</dt><dd>{invoice.currency} {invoice.discountAmount.toFixed(2)}{invoice.discountReason ? ` — ${invoice.discountReason}` : ""}</dd></> : null}{invoice.notes ? <><dt className="text-muted-foreground">Notes</dt><dd className="whitespace-pre-wrap">{invoice.notes}</dd></> : null}</dl><a href={`/api/platform-reports/invoice?id=${invoice._id}&format=pdf`} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm text-primary hover:underline">Download PDF</a></CardContent></Card><InvoiceActions invoiceId={String(invoice._id)} status={invoice.status} /></div>;
}
