"use client";
import { startTransition, useActionState, useEffect } from "react";
import { CalendarDays } from "lucide-react";
import { registerForExam, cancelExamRegistration, type ExamRegistrationState } from "@/lib/actions/exam-registration.actions";
import { toast } from "@/lib/toast";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
type Exam = { id: string; title: string; date: string; term: string; academicYear: string; subject: string; subjectCode: string; registered: boolean; upcoming: boolean };
type Registration = { id: string; status: "registered" | "cancelled"; registeredAt: string; examTitle: string; examDate: string | null; subject: string; cancellable: boolean };
const initialState: ExamRegistrationState = {};
function RegisterForm({ exam }: { exam: Exam }) { const [state, action, pending] = useActionState(registerForExam, initialState); useEffect(() => { if (state.error) toast.error("Could not register", state.error); if (state.success) toast.success(state.success); }, [state]); return <form action={action} className="mt-4 flex flex-col gap-3"><input type="hidden" name="examId" value={exam.id} /><Textarea name="specialRequirements" placeholder="Special requirements (optional)" className="min-h-18" maxLength={1000} /><Button type="submit" disabled={pending}>{pending ? "Registering..." : "Register for exam"}</Button></form>; }
export function ExamRegistrationList({ exams, registrations }: { exams: Exam[]; registrations: Registration[] }) { const upcoming = exams.filter((exam) => exam.upcoming); return <div className="flex flex-col gap-6"><div><p className="text-eyebrow text-primary">Student services</p><h1 className="text-heading mt-1 text-2xl">Exam registration</h1><p className="mt-1 text-sm text-muted-foreground">Register for upcoming exams scheduled for your class.</p></div><div className="grid gap-4 lg:grid-cols-2">{upcoming.length === 0 ? <Card><CardContent className="py-10 text-center text-sm text-muted-foreground">No upcoming exams are available for registration.</CardContent></Card> : upcoming.map((exam) => <Card key={exam.id}><CardHeader className="flex-row items-start justify-between gap-3"><div><Badge>{exam.subjectCode || exam.subject}</Badge><CardTitle className="mt-3">{exam.title}</CardTitle></div>{exam.registered ? <Badge variant="success">Registered</Badge> : null}</CardHeader><CardContent><div className="flex items-center gap-2 text-sm text-muted-foreground"><CalendarDays className="size-4" />{new Date(exam.date).toLocaleDateString(undefined, { dateStyle: "long" })}{exam.term ? ` · ${exam.term}` : ""} · {exam.academicYear}</div>{exam.registered ? <p className="mt-4 text-sm text-success">Your registration is confirmed.</p> : <RegisterForm exam={exam} />}</CardContent></Card>)}</div><div><h2 className="text-heading text-lg">Registration history</h2>{registrations.length === 0 ? <p className="mt-3 text-sm text-muted-foreground">You have not registered for an exam yet.</p> : <div className="mt-3 grid gap-3">{registrations.map((registration) => <Card key={registration.id} size="sm"><CardContent className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">{registration.examTitle}</p><p className="text-sm text-muted-foreground">{registration.subject} · Registered {new Date(registration.registeredAt).toLocaleDateString()}</p></div><Badge variant={registration.status === "registered" ? "success" : "secondary"}>{registration.status}</Badge>{registration.cancellable ? <form action={(formData) => startTransition(() => cancelExamRegistration(formData))}><input type="hidden" name="registrationId" value={registration.id} /><Button type="submit" size="sm" variant="outline">Cancel</Button></form> : null}</CardContent></Card>)}</div>}</div></div>; }
