import { CircleAlert, CreditCard, RefreshCw, Users } from "lucide-react";
import { getMrrArr, getOverdueInvoices, getOverdueInvoiceTotal, getPlanDistribution, getUpcomingRenewals } from "@/lib/data/subscription.data";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { StatCard } from "@/components/dashboard-shell/stat-card";
import { InvoiceManagementDialog } from "./invoices/invoice-management-dialog";
import { InvoiceDeskDialog } from "./invoices/invoice-desk-dialog";

export default async function BillingPage() {
  const [metrics, distribution, renewals, overdue, overdueTotal] = await Promise.all([
    getMrrArr(), getPlanDistribution(), getUpcomingRenewals(), getOverdueInvoices(), getOverdueInvoiceTotal(),
  ]);
  const largestPlan = Math.max(...distribution.map((item) => item.count), 1);

  return (
    <div className="flex flex-col gap-6">
      <div className="relative overflow-hidden rounded-[28px] border border-primary/15 bg-[linear-gradient(120deg,color-mix(in_oklch,var(--primary),transparent_91%),transparent_55%),var(--card)] px-5 py-6 sm:px-7 sm:py-8">
        <div className="absolute -top-16 -right-10 size-56 rounded-full bg-primary/10 blur-3xl" />
        <div className="relative flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-eyebrow text-primary">Revenue operations</p><h1 className="text-heading mt-2 text-3xl">Billing, without blind spots.</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Track recurring revenue, upcoming renewals, and invoices that need attention.</p></div><InvoiceDeskDialog><div className="divide-y divide-border/70">{overdue.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">No overdue invoices. The collection queue is clear.</p> : overdue.slice(0, 12).map((invoice) => { const institute = invoice.instituteId as unknown as { name?: string } | null; const plan = invoice.planId as unknown as { name?: string } | null; const data = { id: String(invoice._id), invoiceNumber: invoice.invoiceNumber, instituteName: institute?.name ?? "Unknown institute", planName: invoice.planNameSnapshot || plan?.name, amount: invoice.amount, currency: invoice.currency, status: invoice.status, dueAt: invoice.dueAt.toISOString(), issuedAt: invoice.issuedAt.toISOString(), paidAt: invoice.paidAt?.toISOString(), paymentMethod: invoice.paymentMethod ?? undefined, notes: invoice.notes ?? undefined }; return <div key={data.id} className="flex items-center justify-between gap-4 py-3"><div><p className="font-medium">{data.instituteName}</p><p className="text-xs text-muted-foreground">{data.invoiceNumber} · Due {new Date(data.dueAt).toLocaleDateString()}</p></div><InvoiceManagementDialog invoice={data} /></div>; })}</div></InvoiceDeskDialog></div>
      </div>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><StatCard label="MRR" icon={CreditCard} value={`$${metrics.mrr.toFixed(2)}`} sub="Active subscriptions" tone="primary" /><StatCard label="ARR" icon={CreditCard} value={`$${metrics.arr.toFixed(2)}`} sub="Projected annual run rate" tone="info" /><StatCard label="Active subscriptions" icon={Users} value={metrics.activeSubscriptions} sub={`${renewals.length} renew within 30 days`} tone="success" /><StatCard label="Payment follow-up" icon={CircleAlert} value={overdue.length} sub={`$${overdueTotal.totalAmount.toFixed(2)} overdue`} tone="warning" /></div>
      <div className="grid gap-6 lg:grid-cols-2">
        <Card><CardHeader><CardTitle>Plan distribution</CardTitle><p className="text-sm text-muted-foreground">Where active subscriptions are concentrated.</p></CardHeader><CardContent>{distribution.length === 0 ? <p className="text-sm text-muted-foreground">No subscriptions yet.</p> : <div className="flex flex-col gap-4">{distribution.map((item) => <div key={String(item.planId)}><div className="flex items-center justify-between text-sm"><span className="font-medium">{item.name}</span><span className="text-muted-foreground">{item.count} institutes</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${(item.count / largestPlan) * 100}%` }} /></div></div>)}</div>}</CardContent></Card>
        <Card><CardHeader><CardTitle>Upcoming renewals</CardTitle><p className="text-sm text-muted-foreground">Auto-renewing subscriptions ending in the next 30 days.</p></CardHeader><CardContent>{renewals.length === 0 ? <p className="text-sm text-muted-foreground">No renewals due in the next 30 days.</p> : <div className="divide-y divide-border/70">{renewals.slice(0, 6).map((renewal) => { const institute = renewal.instituteId as unknown as { name?: string } | null; const plan = renewal.planId as unknown as { name?: string } | null; return <div key={String(renewal._id)} className="flex items-center justify-between gap-4 py-3 first:pt-0 last:pb-0 text-sm"><div><p className="font-medium">{institute?.name ?? "Unknown institute"}</p><p className="text-xs text-muted-foreground">{plan?.name ?? "Unknown plan"}</p></div><span className="text-xs text-muted-foreground">{renewal.currentPeriodEnd ? new Date(renewal.currentPeriodEnd).toLocaleDateString() : "-"}</span></div>; })}</div>}</CardContent></Card>
      </div>
      <Card><CardHeader className="flex flex-row items-center justify-between gap-4"><div><CardTitle>Overdue invoices</CardTitle><p className="mt-1 text-sm text-muted-foreground">Prioritize accounts that need a payment conversation.</p></div><span className="text-sm font-medium text-primary">Select an invoice to manage it</span></CardHeader><CardContent>{overdue.length === 0 ? <p className="text-sm text-muted-foreground">No overdue invoices. The collection queue is clear.</p> : <div className="divide-y divide-border/70">{overdue.slice(0, 6).map((invoice) => { const institute = invoice.instituteId as unknown as { name?: string } | null; const plan = invoice.planId as unknown as { name?: string } | null; const data = { id: String(invoice._id), invoiceNumber: invoice.invoiceNumber, instituteName: institute?.name ?? "Unknown institute", planName: invoice.planNameSnapshot || plan?.name, amount: invoice.amount, currency: invoice.currency, status: invoice.status, dueAt: invoice.dueAt.toISOString(), issuedAt: invoice.issuedAt.toISOString(), paidAt: invoice.paidAt?.toISOString(), paymentMethod: invoice.paymentMethod ?? undefined, notes: invoice.notes ?? undefined }; return <div key={String(invoice._id)} className="flex items-center justify-between gap-4 py-3 text-sm first:pt-0 last:pb-0"><div><p className="font-medium">{institute?.name ?? "Unknown institute"}</p><p className="text-xs text-muted-foreground">{invoice.invoiceNumber} · Due {new Date(invoice.dueAt).toLocaleDateString()}</p></div><div className="flex items-center gap-3"><span className="font-medium">{invoice.currency} {invoice.amount.toFixed(2)}</span><InvoiceManagementDialog invoice={data} /></div></div>; })}</div>}</CardContent></Card>
      <div className="flex items-center gap-2 text-sm text-muted-foreground"><RefreshCw className="size-4" /> Revenue reflects active subscriptions only.</div>
    </div>
  );
}
